/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devoir1;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        RunListAssures.menu();

    }

}
